name: AdvancedShopFinder
version: miencraft_plugin_version
main: dev.nikomaru.advancedshopfinder.AdvancedShopFinder
website: https://github.com/Nlkomaru/AdvancedShopFinder
depend:
  - QuickShop-Hikari
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.11.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.11.0
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1
api-version: "1.20"
